version: '2'

services:
  videosync:
    image: lukasklinger/videosync:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /path/to/video.mp4:/app/video/video.mp4:ro
    environment:
      - WATCH_PIN
      - ADMIN_PIN=4542
